apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive
  name: hive
spec:
  ports:
  - name: meta
    port: 9083
    protocol: TCP
    targetPort: 9083
  - name: thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: ui
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: hive
  sessionAf***REMOVED***nity: None
  type: ClusterIP
