apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: hive
  name: hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive
  serviceName: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      containers:
      - name: metastore
        args: ["/opt/hive/bin/hive", "--service", "metastore"]
        image: quay.io/coreos/chargeback-hive:0.3
        ports:
        - name: meta
          containerPort: 9083
          protocol: TCP
        env:
        - name: CORE_CONF_fs_s3n_awsAccessKeyId
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: CORE_CONF_fs_s3n_awsSecretAccessKey
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: hive-data
          mountPath: /var/lib/hive
      - name: hive
        args: ["/opt/hive/bin/hive", "--service", "hiveserver2"]
        image: quay.io/coreos/chargeback-hive:0.3
        imagePullPolicy: Always
        ports:
        - name: thrift
          containerPort: 10000
          protocol: TCP
        - name: ui
          containerPort: 10002
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        env:
        - name: CORE_CONF_fs_s3n_awsAccessKeyId
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: CORE_CONF_fs_s3n_awsSecretAccessKey
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "1000Mi"
            cpu: "100m"
          limits:
            memory: "1500Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: derek-gonyeo-pull-secret
      volumes:
      - name: hive-data
        emptyDir:
          medium: ""
