apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hive
  name: hive
  namespace: tectonic-chargeback
spec:
  replicas: 1
  selector:
    matchLabels:
      hive-app: server
  template:
    metadata:
      labels:
        hive-app: server
    spec:
      containers:
      - name: hive
        image: quay.io/fest-data-demo/hive:0.3
        imagePullPolicy: Always
        ports:
        - name: thrift
          containerPort: 10000
          protocol: TCP
        - name: ui
          containerPort: 10002
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        env:
        - name: CORE_CONF_fs_s3n_awsAccessKeyId
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: CORE_CONF_fs_s3n_awsSecretAccessKey
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        - name: HADOOP_CLASSPATH
          value: "/opt/hive/hcatalog/share/hcatalog/*:/opt/hadoop-2.8.0/share/hadoop/tools/lib/*"
        - name: CORE_CONF_fs_defaultFS
          value: file://user/hive/warehouse
        - name: HIVE_AUX_JARS_PATH
          value: /usr/hdp/current/hive-server2/auxlib
        resources:
          requests:
            memory: "1000Mi"
            cpu: "100m"
          limits:
            memory: "1500Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
