apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "cluster-cpu-utilization"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  dynamicReportQueries:
  - cluster-cpu-capacity
  - cluster-cpu-usage
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: total_cluster_capacity_cpu_core_hours
    type: double
    unit: cpu_core_hours
  - name: total_cluster_usage_cpu_core_hours
    type: double
    unit: cpu_core_hours
  - name: cluster_cpu_utilization_percent
    type: double
  - name: avg_cluster_capacity_cpu_cores
    type: double
    unit: cpu_cores
  - name: avg_cluster_usage_cpu_cores
    type: double
    unit: cpu_cores
  - name: avg_node_count
    type: double
  - name: avg_pod_count
    type: double
  - name: avg_pod_per_node_count
    type: double
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: ClusterCpuUtilizationReportName
  - name: ClusterCpuCapacityReportName
  - name: ClusterCpuUsageReportName
  query: |
    {|/* Handle aggregating a sub-report */|}
    {|- if .Report.Inputs.ClusterCpuUtilizationReportName -|}
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      sum(total_cluster_capacity_cpu_core_hours) AS total_cluster_capacity_cpu_core_hours,
      sum(total_cluster_usage_cpu_core_hours) AS total_cluster_usage_cpu_core_hours,
      avg(cluster_cpu_utilization_percent) AS cluster_cpu_utilization_percent,
      avg(avg_cluster_capacity_cpu_cores) AS avg_cluster_capacity_cpu_cores,
      avg(avg_cluster_usage_cpu_cores) AS avg_cluster_usage_cpu_cores,
      avg(avg_node_count) AS avg_node_count,
      avg(avg_pod_count) AS avg_pod_count,
      avg(avg_pod_per_node_count) AS avg_pod_per_node_count
    FROM {| .Report.Inputs.ClusterCpuUtilizationReportName | reportTableName |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    {|- ***REMOVED*** -|}
    {|- if or (and (not .Report.Inputs.ClusterCpuCapacityReportName) .Report.Inputs.ClusterCpuUsageReportName) (and (not .Report.Inputs.ClusterCpuUsageReportName) .Report.Inputs.ClusterCpuCapacityReportName) -|}
    {|- fail "input ClusterCpuCapacityReportName and ClusterCpuUsageReportName must both be set" -|}
    {|- end -|}
    WITH cluster_cpu_capacity AS (
      {| renderReportGenerationQuery "cluster-cpu-capacity" . |}
    ), cluster_cpu_usage AS (
      {| renderReportGenerationQuery "cluster-cpu-usage" . |}
    )
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      capacity.total_cluster_capacity_cpu_core_hours,
      usage.total_cluster_usage_cpu_core_hours,
      usage.total_cluster_usage_cpu_core_hours / capacity.total_cluster_capacity_cpu_core_hours AS cluster_cpu_utilization_percent,
      capacity.avg_cluster_capacity_cpu_cores,
      usage.avg_cluster_usage_cpu_cores,
      capacity.avg_node_count,
      usage.avg_pod_count,
      usage.avg_pod_count / capacity.avg_node_count AS avg_pod_per_node_count
    FROM cluster_cpu_usage AS usage
    JOIN cluster_cpu_capacity AS capacity
    ON capacity.period_start = usage.period_start
    AND capacity.period_end = usage.period_end
    {|- end -|}

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "cluster-memory-utilization"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  dynamicReportQueries:
  - cluster-memory-capacity
  - cluster-memory-usage
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: total_cluster_capacity_memory_byte_hours
    type: double
    unit: memory_byte_hours
  - name: total_cluster_usage_memory_byte_hours
    type: double
    unit: memory_byte_hours
  - name: cluster_memory_utilization_percent
    type: double
  - name: avg_cluster_capacity_memory_bytes
    type: double
    unit: memory_bytes
  - name: avg_cluster_usage_memory_bytes
    type: double
    unit: memory_bytes
  - name: avg_node_count
    type: double
  - name: avg_pod_count
    type: double
  - name: avg_pod_per_node_count
    type: double
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: ClusterMemoryUtilizationReportName
  - name: ClusterMemoryCapacityReportName
  - name: ClusterMemoryUsageReportName
  query: |
    {|/* Handle aggregating a sub-report */|}
    {|- if .Report.Inputs.ClusterMemoryUtilizationReportName -|}
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      sum(total_cluster_capacity_memory_byte_hours) AS total_cluster_capacity_memory_byte_hours,
      sum(total_cluster_usage_memory_byte_hours) AS total_cluster_usage_memory_byte_hours,
      avg(cluster_memory_utilization_percent) AS cluster_memory_utilization_percent,
      avg(avg_cluster_capacity_memory_bytes) AS avg_cluster_capacity_memory_bytes,
      avg(avg_cluster_usage_memory_bytes) AS avg_cluster_usage_memory_bytes,
      avg(avg_node_count) AS avg_node_count,
      avg(avg_pod_count) AS avg_pod_count,
      avg(avg_pod_per_node_count) AS avg_pod_per_node_count
    FROM {| .Report.Inputs.ClusterMemoryUtilizationReportName | reportTableName |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    {|- ***REMOVED*** -|}
    {|/* Validate both inputs are speci***REMOVED***ed if only one is speci***REMOVED***ed*/|}
    {|- if or (and (not .Report.Inputs.ClusterMemoryCapacityReportName) .Report.Inputs.ClusterMemoryUsageReportName) (and (not .Report.Inputs.ClusterMemoryUsageReportName) .Report.Inputs.ClusterMemoryCapacityReportName) -|}
    {|- fail "input ClusterMemoryCapacityReportName and ClusterMemoryUsageReportName must both be set" -|}
    {|- end -|}
    WITH cluster_memory_capacity AS (
      {| renderReportGenerationQuery "cluster-memory-capacity" . |}
    ), cluster_memory_usage AS (
      {| renderReportGenerationQuery "cluster-memory-usage" . |}
    )
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      capacity.total_cluster_capacity_memory_byte_hours,
      usage.total_cluster_usage_memory_byte_hours,
      usage.total_cluster_usage_memory_byte_hours / capacity.total_cluster_capacity_memory_byte_hours AS cluster_memory_utilization_percent,
      capacity.avg_cluster_capacity_memory_bytes,
      usage.avg_cluster_usage_memory_bytes,
      capacity.avg_node_count,
      usage.avg_pod_count,
      usage.avg_pod_count / capacity.avg_node_count AS avg_pod_per_node_count
    FROM cluster_memory_usage AS usage
    JOIN cluster_memory_capacity AS capacity
    ON capacity.period_start = usage.period_start
    AND capacity.period_end = usage.period_end
    {|- end -|}
