apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "cluster-cpu-usage-raw"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-cpu-usage-raw"
  columns:
  - name: timestamp
    type: timestamp
    unit: date
  - name: dt
    type: string
  - name: cpu_cores
    type: double
  - name: cpu_core_seconds
    type: double
  - name: pod_count
    type: double
  query: |
    SELECT
      "timestamp",
      dt,
      sum(pod_usage_cpu_cores) as cpu_cores,
      sum(pod_usage_cpu_core_seconds) as cpu_core_seconds,
      count(*) AS pod_count
    FROM {| generationQueryViewName "pod-cpu-usage-raw" |}
    GROUP BY "timestamp", dt

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "cluster-cpu-usage"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "cluster-cpu-usage-raw"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: total_cluster_usage_cpu_core_hours
    type: double
    unit: cpu_core_hours
  - name: avg_cluster_usage_cpu_cores
    type: double
    unit: cpu_cores
  - name: avg_pod_count
    type: double
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: ClusterCpuUsageReportName
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    {|- if .Report.Inputs.ClusterCpuUsageReportName |}
      sum(total_cluster_usage_cpu_core_hours) as total_cluster_usage_cpu_core_hours,
      avg(avg_cluster_usage_cpu_cores) as avg_cluster_usage_cpu_cores,
      avg(avg_pod_count) AS avg_pod_count
      FROM {| .Report.Inputs.ClusterCpuUsageReportName | scheduledReportTableName |}
      WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
      AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    {|- else |}
      sum(cpu_core_seconds) / 60 / 60 as total_cluster_usage_cpu_core_hours,
      avg(cpu_cores) as avg_cluster_usage_cpu_cores,
      avg(pod_count) AS avg_pod_count
      FROM {| generationQueryViewName "cluster-cpu-usage-raw" |}
      WHERE "timestamp"  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
      AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
      AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
      AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    {|- end |}

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "cluster-memory-usage-raw"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-memory-usage-raw"
  columns:
  - name: timestamp
    type: timestamp
    unit: date
  - name: dt
    type: string
  - name: memory_bytes
    type: double
  - name: memory_byte_seconds
    type: double
  - name: pod_count
    type: double
  query: |
    SELECT
      "timestamp",
      dt,
      sum(pod_usage_memory_bytes) as memory_bytes,
      sum(pod_usage_memory_byte_seconds) as memory_byte_seconds,
      count(*) AS pod_count
    FROM {| generationQueryViewName "pod-memory-usage-raw" |}
    GROUP BY "timestamp", dt

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "cluster-memory-usage"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "cluster-memory-usage-raw"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: total_cluster_usage_memory_byte_hours
    type: double
    unit: memory_byte_hours
  - name: avg_cluster_usage_memory_bytes
    type: double
    unit: memory_bytes
  - name: avg_pod_count
    type: double
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: ClusterMemoryUsageReportName
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    {|- if .Report.Inputs.ClusterMemoryUsageReportName |}
      sum(total_cluster_usage_memory_byte_hours) as total_cluster_usage_memory_byte_hours,
      avg(avg_cluster_usage_memory_bytes) as avg_cluster_usage_memory_bytes,
      avg(avg_pod_count) AS avg_pod_count
      FROM {| .Report.Inputs.ClusterMemoryUsageReportName | scheduledReportTableName |}
      WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
      AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    {|- else |}
      sum(memory_byte_seconds) / 60 / 60 as total_cluster_usage_memory_byte_hours,
      avg(memory_bytes) as avg_cluster_usage_memory_bytes,
      avg(pod_count) AS avg_pod_count
      FROM {| generationQueryViewName "cluster-memory-usage-raw" |}
      WHERE "timestamp"  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
      AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
      AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
      AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    {|- end |}
