apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "pod-cpu-request-raw"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportDataSources:
  - "pod-request-cpu-cores"
  columns:
  - name: pod
    type: string
    unit: kubernetes_pod
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: node
    type: string
    unit: kubernetes_node
  - name: labels
    type: map<string, string>
    tableHidden: true
  - name: pod_request_cpu_cores
    type: double
    unit: cpu_cores
  - name: timeprecision
    type: double
    unit: seconds
  - name: pod_request_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: timestamp
    type: timestamp
    unit: date
  - name: dt
    type: string
  query: |
      SELECT labels['pod'] as pod,
          labels['namespace'] as namespace,
          element_at(labels, 'node') as node,
          labels,
          amount as pod_request_cpu_cores,
          timeprecision,
          amount * timeprecision as pod_request_cpu_core_seconds,
          "timestamp",
          dt
      FROM {| dataSourceTableName "pod-request-cpu-cores" |}
      WHERE element_at(labels, 'node') IS NOT NULL

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "pod-cpu-usage-raw"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportDataSources:
  - "pod-usage-cpu-cores"
  columns:
  - name: pod
    type: string
    unit: kubernetes_pod
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: node
    type: string
    unit: kubernetes_node
  - name: labels
    type: map<string, string>
    tableHidden: true
  - name: pod_usage_cpu_cores
    type: double
    unit: cpu_cores
  - name: timeprecision
    type: double
    unit: seconds
  - name: pod_usage_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  - name: timestamp
    type: timestamp
    unit: date
  - name: dt
    type: string
  query: |
      SELECT labels['pod'] as pod,
          labels['namespace'] as namespace,
          element_at(labels, 'node') as node,
          labels,
          amount as pod_usage_cpu_cores,
          timeprecision,
          amount * timeprecision as pod_usage_cpu_core_seconds,
          "timestamp",
          dt
      FROM {| dataSourceTableName "pod-usage-cpu-cores" |}
      WHERE element_at(labels, 'node') IS NOT NULL

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "pod-cpu-request"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-cpu-request-raw"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: string
    unit: kubernetes_pod
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: node
    type: string
    unit: kubernetes_node
  - name: data_start
    type: timestamp
    unit: date
  - name: data_end
    type: timestamp
    unit: date
  - name: pod_request_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      pod,
      namespace,
      node,
      min("timestamp") as data_start,
      max("timestamp") as data_end,
      sum(pod_request_cpu_core_seconds) as pod_request_cpu_core_seconds
    FROM {| generationQueryViewName "pod-cpu-request-raw" |}
    WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
    AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    GROUP BY namespace, pod, node
    ORDER BY namespace, pod, node ASC, pod_request_cpu_core_seconds DESC

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "pod-cpu-usage"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-cpu-usage-raw"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: string
    unit: kubernetes_pod
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: node
    type: string
    unit: kubernetes_node
  - name: data_start
    type: timestamp
    unit: date
  - name: data_end
    type: timestamp
    unit: date
  - name: pod_usage_cpu_core_seconds
    type: double
    unit: cpu_core_seconds
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      pod,
      namespace,
      node,
      min("timestamp") as data_start,
      max("timestamp") as data_end,
      sum(pod_usage_cpu_core_seconds) as pod_usage_cpu_core_seconds
    FROM {| generationQueryViewName "pod-cpu-usage-raw" |}
    WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
    AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    GROUP BY namespace, pod, node
    ORDER BY namespace, pod, node ASC, pod_usage_cpu_core_seconds DESC

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "namespace-cpu-request"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-cpu-request-raw"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: data_start
    type: timestamp
    unit: date
  - name: data_end
    type: timestamp
    unit: date
  - name: pod_request_cpu_core_seconds
    type: double
    unit: core_seconds
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: NamespaceCPURequestReportName
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    {|- if .Report.Inputs.NamespaceCPURequestReportName |}
      namespace,
      min("period_start") as data_start,
      max("period_end") as data_end,
      sum(pod_request_cpu_core_seconds) as pod_request_cpu_core_seconds
    FROM {| .Report.Inputs.NamespaceCPURequestReportName | reportTableName |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    GROUP BY namespace
    {|- else |}
      namespace,
      min("timestamp") as data_start,
      max("timestamp") as data_end,
      sum(pod_request_cpu_core_seconds) as pod_request_cpu_core_seconds
    FROM {| generationQueryViewName "pod-cpu-request-raw" |}
    WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
    AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    GROUP BY namespace
    {|- end |}

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "namespace-cpu-usage"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-cpu-usage-raw"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: data_start
    type: timestamp
    unit: date
  - name: data_end
    type: timestamp
    unit: date
  - name: pod_usage_cpu_core_seconds
    type: double
    unit: core_seconds
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: NamespaceCPUUsageReportName
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    {|- if .Report.Inputs.NamespaceCPUUsageReportName |}
      namespace,
      min("period_start") as data_start,
      max("period_end") as data_end,
      sum(pod_usage_cpu_core_seconds) as pod_usage_cpu_core_seconds
    FROM {| .Report.Inputs.NamespaceCPUUsageReportName | reportTableName |}
    WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    GROUP BY namespace
    {|- else |}
      namespace,
      min("timestamp") as data_start,
      max("timestamp") as data_end,
      sum(pod_usage_cpu_core_seconds) as pod_usage_cpu_core_seconds
    FROM {| generationQueryViewName "pod-cpu-usage-raw" |}
    WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
    AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
    AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    GROUP BY namespace
    {|- end |}

---

apiVersion: metering.openshift.io/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "namespace-cpu-utilization"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  dynamicReportQueries:
  - "namespace-cpu-request"
  - "namespace-cpu-usage"
  - "cluster-cpu-capacity"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: namespace
    type: string
    unit: kubernetes_namespace
  - name: pod_usage_cpu_core_seconds
    type: double
    unit: core_seconds
  - name: pod_request_cpu_core_seconds
    type: double
    unit: core_seconds
  - name: pod_cpu_usage_percent
    type: double
  - name: pod_cpu_request_percent
    type: double
  - name: total_cluster_capacity_cpu_core_seconds
    type: double
  inputs:
  - name: ReportingStart
  - name: ReportingEnd
  - name: NamespaceCPURequestReportName
  - name: NamespaceCPUUsageReportName
  - name: ClusterCpuCapacityReportName
  query: |
    WITH cluster_cpu_capacity AS (
      {| renderReportGenerationQuery "cluster-cpu-capacity" . |}
    ), namespace_cpu_usage AS (
      {| renderReportGenerationQuery "namespace-cpu-usage" . |}
    ), namespace_cpu_request AS (
      {| renderReportGenerationQuery "namespace-cpu-request" . |}
    )
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      usage.namespace,
      usage.pod_usage_cpu_core_seconds,
      request.pod_request_cpu_core_seconds,
      usage.pod_usage_cpu_core_seconds / capacity.total_cluster_capacity_cpu_core_seconds AS pod_cpu_usage_percent,
      request.pod_request_cpu_core_seconds / capacity.total_cluster_capacity_cpu_core_seconds AS pod_cpu_request_percent,
      capacity.total_cluster_capacity_cpu_core_seconds
    FROM namespace_cpu_request as request
    JOIN namespace_cpu_usage as usage
      ON request.period_start = usage.period_start
      AND request.period_end = usage.period_end
      AND request.namespace = usage.namespace
    JOIN cluster_cpu_capacity as capacity
      ON capacity.period_start = request.period_start
      AND capacity.period_end = request.period_end
