apiVersion: v1
kind: Service
metadata:
  name: chargeback-state-metrics
  namespace: team-chargeback
  labels:
    chargeback-app: metrics
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    chargeback-app: metrics
