---
dependencies:
- name: reporting-operator
  version: 0.1.0
  repository: "***REMOVED***le://../reporting-operator"
- name: openshift-reporting
  version: 0.1.0
  repository: "***REMOVED***le://../openshift-reporting"
  condition: openshift-reporting.enabled
- name: presto
  version: 0.1.0
  repository: "***REMOVED***le://../presto"
- name: hdfs
  version: 0.1.0
  repository: "***REMOVED***le://../hdfs"
  condition: hdfs.enabled
- name: superset
  version: 1.0.0
  repository: "***REMOVED***le://../superset"
  condition: superset.enabled
