chargeback-operator:
  con***REMOVED***g:
    awsBillingDataSource:
      # Change to false if you wish to enable the AWS Billing Report
      # datasource, for use with the AWS cost correlation reports.
      enabled: false
      # Replace these values with your own
      bucket: "your-aws-cost-report-bucket"
      path: "path/to/report"
    # Replace these with your own AWS credentials
    awsAccessKeyID: "REPLACEME"
    awsSecretAccessKey: "REPLACEME"

presto:
  con***REMOVED***g:
    # Replace these with your own AWS credentials
    awsAccessKeyID: "REPLACEME"
    awsSecretAccessKey: "REPLACEME"

  # Uncomment the section below if you wish to adjust the resource limits and
  # requests. These examples use the defaults.

  # presto:
  #   resources:
  #     requests:
  #       memory: "1536Mi"
  #       cpu: "300m"
  #     limits:
  #       memory: "2048Mi"
  #       cpu: "1000m"
  # hive:
  #   metastore:
  #     resources:
  #       requests:
  #         memory: "650Mi"
  #         cpu: "100m"
  #       limits:
  #         memory: "650Mi"
  #         cpu: "500m"
  #     storage:
  #       # Default is null, which means using the default storage class if it exists. If you wish to use a different storage class, specify it here
  #       class: null
  #       size: "5Gi"

  #   server:
  #     resources:
  #       requests:
  #         memory: "400Mi"
  #         cpu: "100m"
  #       limits:
  #         memory: "400Mi"
  #         cpu: "100m"

# Uncomment the section below if you wish to adjust the resource limits and
# requests. These examples use the defaults.

# hdfs:
#   datanode:
#     resources:
#       requests:
#         memory: "250Mi"
#         cpu: "250m"
#       limits:
#         memory: "250Mi"
#         cpu: "250m"

#     storage:
#         # Default is null, which means using the default storage class if it exists. If you wish to use a different storage class, specify it here
#       class: null
#       size: "5Gi"

#   namenode:
#     resources:
#       requests:
#         memory: "350Mi"
#         cpu: "250m"
#       limits:
#         memory: "350Mi"
#         cpu: "250m"

#     storage:
#       size: "5Gi"
#       class: null
