apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: datanode
  name: hdfs-datanode
  namespace: tectonic-chargeback
spec:
  ports:
  - name: data
    port: 50010
    protocol: TCP
    targetPort: 50010
  - name: meta
    port: 50020
    protocol: TCP
    targetPort: 50020
  selector:
    app: datanode
  sessionAffinity: None
  clusterIP: None
