apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: namenode
  name: hdfs-namenode
spec:
  ports:
  - name: fs
    port: 8020
    protocol: TCP
    targetPort: 8020
  selector:
    app: namenode
  sessionAffinity: None
  type: ClusterIP
