# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/set-gen",
  # required for client-gen
  "k8s.io/apimachinery/pkg/apimachinery/registered",
  "k8s.io/apimachinery/pkg/labels",
  "k8s.io/apimachinery/pkg/watch",
  "k8s.io/apimachinery/pkg/fields",
  "github.com/golang/mock/mockgen",
  "github.com/golang/mock/mockgen/model",
]

[[constraint]]
  branch = "master"
  name = "github.com/robfig/cron"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.3"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

[[constraint]]
  branch = "master"
  name = "github.com/prestodb/presto-go-client"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "git.apache.org/thrift.git"
  source = "github.com/apache/thrift"
  version = "0.11.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "1.1.0"
