apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  openshift-reporting:
    spec:
      awsBillingReportDataSource:
        enabled: true
        # Replace these with where your AWS billing reports are
        # stored in S3.
        bucket: "your-aws-cost-report-bucket"
        pre***REMOVED***x: "path/to/report"
        region: "your-buckets-region"
  reporting-operator:
    spec:
      con***REMOVED***g:
        # Replace these with your own AWS credentials
        awsAccessKeyID: "REPLACEME"
        awsSecretAccessKey: "REPLACEME"

  presto:
    spec:
      con***REMOVED***g:
        # Replace these with your own AWS credentials
        awsAccessKeyID: "REPLACEME"
        awsSecretAccessKey: "REPLACEME"
