apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      nodeSelector:
        "node-role.kubernetes.io/infra": "true"

  presto:
    spec:
      presto:
        coordinator:
          nodeSelector:
            "node-role.kubernetes.io/infra": "true"
        worker:
          nodeSelector:
            "node-role.kubernetes.io/infra": "true"
      hive:
        metastore:
          nodeSelector:
            "node-role.kubernetes.io/infra": "true"
        server:
          nodeSelector:
            "node-role.kubernetes.io/infra": "true"

  hadoop:
    spec:
      hdfs:
        namenode:
          nodeSelector:
            "node-role.kubernetes.io/infra": "true"
        datanode:
          nodeSelector:
            "node-role.kubernetes.io/infra": "true"
