apiVersion: metering.openshift.io/v1
kind: MeteringCon***REMOVED***g
metadata:
  name: "operator-metering"
spec:
  storage:
    type: "hive"
    hive:
      type: "s3Compatible"
      s3Compatible:
        bucket: "bucketname"
        endpoint: "https://example:port-number"
        secretName: "my-aws-secret"
        # If you need to trust a self-signed certi***REMOVED***cate, uncomment the "ca"
        # section below. Be sure to include the full certi***REMOVED***cate chain.
        #
        # ca:
        #   createSecret: true
        #   content: |
        #     -----BEGIN CERTIFICATE-----
        #     MIIDdTCCAl2gAwIBAgIIOT6yX8oQ/S4wDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
        #     Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTU2NDAwMzI4MTAe
        #     Fw0xOTA4MzAyMDQ5MzlaFw0yMTA4MjkyMDQ5NDBaMBgxFjAUBgNVBAMTDXMzLm5v
        #     b2JhYS5zdmMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDhYlylOSHB
        #     ++XGfsuyFLvK8Yrri2d0NRJBBqmQ4c1Mhv242HSVMxyRsxBXyLnomjvFiKJhMlIB
        #     m/LJRxBJz3ZONvkCiBF8SOmim6TK+9I8Ky7+nz8urovJY28jiJjjsLAJitk/nU40
        #     boZ41BD4oTVVmY7u2iB7JyurTGZejSYGf1rq1cHeNOZ2PPHpsIFvfvcNh4ig6lOj
        #     Jfz9shaG7P4zDRK7vZVJylmLDq2s1oauhDs57QCLMBMmxrm96+NdRP7BiV1qmpwZ
        #     QavLTQcLNMOFGgN8ETJ/nT85zd8tHKePL0tL/KULVfo18rHjcYTUyLManZCXrGdG
        #     HGmfsOBbtkJLAgMBAAGjgaQwgaEwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoG
        #     CCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwNQYDVR0RBC4wLIINczMubm9vYmFhLnN2
        #     Y4IbczMubm9vYmFhLnN2Yy5jbHVzdGVyLmxvY2FsMDUGCysGAQQBkggRZAIBBCYT
        #     JDE3YzdiZWYzLWJkM2YtMTFlOS04ODUxLTAyMDVlYmEwYTZiNjANBgkqhkiG9w0B
        #     AQsFAAOCAQEAajW7mCp7S//NxJGaJUrH+08zV5Q8PzdFWqnZ6k3ZpyvqLmIiV0VZ
        #     2YQtyd+SxyekIbgYXHHhrUPFKL/coUGzHqjw/F+ZvysShsIvzHyFKyMXP1Zc7WeU
        #     83PLjjReNHv7iII62/wCPdYIFr1dNFPnfQaSrIcrN+OyiH4FVQd187BArBkudSBw
        #     Y7gGq8XI80IAutbxnYGgtElKOrbh8MELlrPfqMlI+1/U0upP+AEde78LpDgTnI2H
        #     16gNjkM+CDOgWN2njqdiohI42Uo3uan4LVTB07FOp5ulB9TmlAn1HcpFc1YQEiVo
        #     uvbyiXoRx34oaSKNwXBA5QYwYh8A3a74dA==
        #     -----END CERTIFICATE-----
        #     -----BEGIN CERTIFICATE-----
        #     MIIDCjCCAfKgAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MTQwMgYDVQQDDCtvcGVu
        #     c2hpZnQtc2VydmljZS1zZXJ2aW5nLXNpZ25lckAxNTY0MDAzMjgxMB4XDTE5MDcy
        #     NDIxMjEyMFoXDTIwMDcyMzIxMjEyMVowNjE0MDIGA1UEAwwrb3BlbnNoaWZ0LXNl
        #     cnZpY2Utc2VydmluZy1zaWduZXJAMTU2NDAwMzI4MTCCASIwDQYJKoZIhvcNAQEB
        #     BQADggEPADCCAQoCggEBAKzp3pWqhEGqOXWTu7GwegQC43L+IXwgy9ROF8aesLV5
        #     WqVVIG5asg4APBVOw8bQUIKUTAEMC6Z8uhY8/H5UVVgspLPoyfHkP0Fiza8uwFB7
        #     dy3f37F7LAgiopAFRvVLbfz0jo0s6HY3PuOQnzv0+K3Fqvp6/VrJXiUvhNI5Q2ic
        #     ifSJ+f/hg/KVEf2vezreT91e+ijQVbTEPsnV3y24DnDAVo3gnuXON89DtLszcXHG
        #     T/AXX3ca/hh9kFExwV6y3/ahbX3a7f0hlrLDQ4ifmqnIhibI3+SsjdSj98rk77yl
        #     YfKNomCr4AV1zvCMB7ssBStdyqIpjF1afflrhdKI9+cCAwEAAaMjMCEwDgYDVR0P
        #     AQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACo6
        #     Vwx1yqd698UvxHfTpwzmKl049zG1S4coMiRXBemzaU50U/Twj2n4fhN8ogh6FNsN
        #     4usl+4PimrYvACnteQ7ICsEkfOWCugpwH8N7o66NsrqTMe9micSuDXr0lRCimmcw
        #     pFIoTWC1sonOT+7vESQJccB4BE93hwQD1ZRriAWAVtdxG1rqN+vkEdW6DoRHfU5i
        #     7PrDmMgrXl3vV2gTQuLtAvWeSTZe/4bWGZkqhYBOvPNNaGQbmU3y7To6L8BKoa1+
        #     14EsTPkbKPDa4bTnFbS0x4FguHa8vIyF8uAkU6mnExzjcJCRZqBakfK/17qdqzcR
        #     MxX6xP1czY3Cop0HoaY=
        #     -----END CERTIFICATE-----
