{{- $operatorValues :=  index .Values "reporting-operator" -}}
{{- if $operatorValues.spec.con***REMOVED***g.prometheus.metricsImporter.auth.tokenSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $operatorValues.spec.con***REMOVED***g.prometheus.metricsImporter.auth.tokenSecret.name }}
  labels:
    app: reporting-operator
data:
  token: {{ required "Must not create an empty bearer token" $operatorValues.spec.con***REMOVED***g.prometheus.metricsImporter.auth.tokenSecret.value | b64enc | quote }}
{{- end -}}
