{{- $operatorValues :=  index .Values "reporting-operator" -}}
{{- if $operatorValues.spec.config.prometheusImporter.auth.tokenSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $operatorValues.spec.config.prometheusImporter.auth.tokenSecret.name }}
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
data:
  token: {{ required "Must not create an empty bearer token" $operatorValues.spec.config.prometheusImporter.auth.tokenSecret.value | b64enc | quote }}
{{- end -}}
