apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metering
  namespace: openshift-metering
spec:
  channel: "4.5"
  name: metering-upstream
  source: metering-upstream-dev
  sourceNamespace: metering

