image:
  repository: quay.io/coreos/chargeback-hadoop
  tag: latest
  pullPolicy: Always

config:
  logLevel: "info"
  namenodeHost: hdfs-namenode-0.hdfs-namenode
  namenodePort: 8020
  datanodeDataDirPerms: "770"

securityContext:
  runAsNonRoot: true

datanode:
  replicas: 1
  terminationGracePeriodSeconds: 30
  resources:
    requests:
      memory: "250Mi"
      cpu: "250m"
    limits:
      memory: "250Mi"
      cpu: "250m"

  storage:
    # Default to null, which means using the default storage class if the
    # defaultStorageClass admission plugin is turned on (is by default on
    # Tectonic).
    class: null
    size: "5Gi"

namenode:
  terminationGracePeriodSeconds: 10
  resources:
    requests:
      memory: "350Mi"
      cpu: "250m"
    limits:
      memory: "350Mi"
      cpu: "250m"

  storage:
    size: "5Gi"
    class: null

