apiVersion: operators.coreos.com/v1
kind: CatalogSource
metadata:
  name: installed-redhat-metering-operators-openshift-metering
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-metering
  packages: metering-ocp

