image:
  repository: quay.io/coreos/chargeback
  tag: latest
  pullPolicy: Always

con***REMOVED***g:
  awsRegion: ""
  awsAccessKeyID: ""
  awsSecretAccessKey: ""

  awsBillingDataSource:
    enabled: false
    bucket: ""
    path: ""

  prometheusURL: "http://prometheus.tectonic-system.svc.cluster.local:9090/"

  promsumPollInterval: "5m"
  promsumChunkSize: "5m"
  promsumStepSize: "60s"

  logReports: "false"
  logDDLQueries: "false"
  logDMLQueries: "false"
  disablePromsum: "false"

resources:
  requests:
    memory: "50Mi"
    cpu: "50m"


