apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hive-server
  labels:
    app: hive
    hive: server
{{- block "extraMetadata" . }}
{{- end }}
spec:
  serviceName: hive-server
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hive
      hive: server
{{- if .Values.spec.hive.labels }}
{{ toYaml .Values.spec.hive.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: hive
        hive: server
{{- if .Values.spec.hive.labels }}
{{ toYaml .Values.spec.hive.labels | indent 8 }}
{{- end }}
      annotations:
        hive-con***REMOVED***gmap-hash: {{ include (print $.Template.BasePath "/hive-con***REMOVED***gmap.yaml") . | sha256sum }}
        hive-scripts-hash: {{ include (print $.Template.BasePath "/hive-scripts-con***REMOVED***gmap.yaml") . | sha256sum }}
        hive-secrets-hash: {{ include (print $.Template.BasePath "/hive-secrets.yaml") . | sha256sum }}
{{- if .Values.spec.hive.annotations }}
{{ toYaml .Values.spec.hive.annotations | indent 8 }}
{{- end }}
    spec:
      securityContext:
{{ toYaml .Values.spec.hive.securityContext | indent 8 }}
{{- if .Values.spec.hive.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spec.hive.server.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: hiveserver2
        command: ["/hive-scripts/entrypoint.sh"]
        args: ["/opt/hive/bin/hive", "--service", "hiveserver2"]
        image: "{{ .Values.spec.hive.image.repository }}:{{ .Values.spec.hive.image.tag }}"
        imagePullPolicy: {{ .Values.spec.hive.image.pullPolicy }}
        ports:
        - name: thrift
          containerPort: 10000
          protocol: TCP
        - name: ui
          containerPort: 10002
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        env:
        - name: HIVE_LOGLEVEL
          value: {{ upper .Values.spec.hive.server.con***REMOVED***g.logLevel | quote}}
{{ include "hive-env" . | indent 8 }}
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: hiveserver2
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: hiveserver2
              resource: limits.memory
        volumeMounts:
        - name: hive-con***REMOVED***g
          mountPath: /hive-con***REMOVED***g
        - name: hive-scripts
          mountPath: /hive-scripts
{{- if .Values.spec.hive.con***REMOVED***g.useHdfsCon***REMOVED***gMap }}
        - name: hdfs-con***REMOVED***g
          mountPath: /hadoop-con***REMOVED***g
{{- end}}
        # openshift requires volumeMounts for VOLUMEs in a Docker***REMOVED***le
        - name: hive-metastore-db-data
          mountPath: /var/lib/hive
        - name: namenode-empty
          mountPath: /hadoop/dfs/name
        - name: datanode-empty
          mountPath: /hadoop/dfs/data
{{- if .Values.spec.con***REMOVED***g.sharedVolume.enabled }}
        - name: hive-warehouse-data
          mountPath: {{ .Values.spec.con***REMOVED***g.sharedVolume.mountPath }}
{{- end }}
{{- if or (not .Values.spec.con***REMOVED***g.sharedVolume.enabled) (and .Values.spec.con***REMOVED***g.sharedVolume.enabled (ne .Values.spec.con***REMOVED***g.sharedVolume.mountPath "/user/hive/warehouse") ) }}
        - name: hive-warehouse-empty
          mountPath: /user/hive/warehouse
{{- end }}
        resources:
{{ toYaml .Values.spec.hive.server.resources | indent 10 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.spec.hive.terminationGracePeriodSeconds }}
      serviceAccount: hive
      volumes:
      - name: hive-con***REMOVED***g
        con***REMOVED***gMap:
          name: hive-con***REMOVED***g
      - name: hive-scripts
        con***REMOVED***gMap:
          name: hive-scripts
          defaultMode: 0555
{{- if .Values.spec.hive.con***REMOVED***g.useHdfsCon***REMOVED***gMap }}
      - name: hdfs-con***REMOVED***g
        con***REMOVED***gMap:
          name: {{ .Values.spec.hive.con***REMOVED***g.hdfsCon***REMOVED***gMapName }}
{{- end }}
      # these emptyDir volumes are necessary because Openshift requires VOLUMEs
      # in a Docker***REMOVED***le have a corresponding volumeMount
      - name: hive-warehouse-empty
        emptyDir: {}
      - name: namenode-empty
        emptyDir: {}
      - name: datanode-empty
        emptyDir: {}
      - name: hive-metastore-db-data
        emptyDir: {}
{{- if .Values.spec.con***REMOVED***g.sharedVolume.enabled }}
      - name: hive-warehouse-data
        persistentVolumeClaim:
          claimName: {{ .Values.spec.con***REMOVED***g.sharedVolume.persistentVolumeClaimName }}
{{- end}}
