apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: presto-coordinator
  labels:
    app: presto
    presto: coordinator
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto
      presto: coordinator
{{- if .Values.spec.presto.labels }}
{{ toYaml .Values.spec.presto.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: presto
        presto: coordinator
{{- if .Values.spec.presto.labels }}
{{ toYaml .Values.spec.presto.labels | indent 8 }}
{{- end }}
      annotations:
        presto-coordinator-config-hash: {{ include (print $.Template.BasePath "/presto-coordinator-config.yaml") . | sha256sum }}
        presto-common-config-hash: {{ include (print $.Template.BasePath "/presto-common-config.yaml") . | sha256sum }}
{{- if .Values.spec.config.createAwsCredentialsSecret }}
        presto-aws-credentials-secrets-hash: {{ include (print $.Template.BasePath "/presto-aws-credentials-secrets.yaml") . | sha256sum }}
{{- end }}
{{- if .Values.spec.presto.annotations }}
{{ toYaml .Values.spec.presto.annotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.spec.presto.securityContext }}
      securityContext:
{{ toYaml .Values.spec.presto.securityContext | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.coordinator.affinity }}
      affinity:
{{ toYaml .Values.spec.presto.coordinator.affinity | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.coordinator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spec.presto.coordinator.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: presto
        image: "{{ .Values.spec.presto.image.repository }}:{{ .Values.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.spec.presto.image.pullPolicy }}
        env:
        - name: PRESTO_CONF_discovery___server_enabled
          value: "true"
        - name: PRESTO_CONF_coordinator
          value: "true"
        - name: PRESTO_CONF_node___scheduler_include___coordinator
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: node-scheduler-include-coordinator
{{- include "presto-env" "presto-coordinator-config" | indent 8 }}
{{- include "presto-common-env" . | indent 8 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: presto-data
          mountPath: /var/presto/data
{{- if .Values.spec.config.sharedVolume.enabled }}
        - name: hive-warehouse-data
          mountPath: {{ .Values.spec.config.sharedVolume.mountPath }}
{{- end }}
        resources:
{{ toYaml .Values.spec.presto.coordinator.resources | indent 10 }}
      volumes:
      - name: presto-data
        emptyDir: {}
{{- if .Values.spec.config.sharedVolume.enabled }}
      - name: hive-warehouse-data
        persistentVolumeClaim:
          claimName: {{ .Values.spec.config.sharedVolume.persistentVolumeClaimName }}
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: presto
{{- if .Values.spec.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.spec.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.spec.presto.coordinator.terminationGracePeriodSeconds }}
