apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: presto-worker
  labels:
    app: presto
    presto: worker
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: {{ .Values.spec.presto.worker.replicas }}
  selector:
    matchLabels:
      app: presto
      presto: worker
{{- if .Values.spec.presto.labels }}
{{ toYaml .Values.spec.presto.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: presto
        presto: worker
{{- if .Values.spec.presto.labels }}
{{ toYaml .Values.spec.presto.labels | indent 8 }}
{{- end }}
      annotations:
        presto-worker-con***REMOVED***g-hash: {{ include (print $.Template.BasePath "/presto-worker-con***REMOVED***g.yaml") . | sha256sum }}
        presto-common-con***REMOVED***g-hash: {{ include (print $.Template.BasePath "/presto-common-con***REMOVED***g.yaml") . | sha256sum }}
        presto-catalog-con***REMOVED***g-hash: {{ include (print $.Template.BasePath "/presto-catalog-con***REMOVED***g-secret.yaml") . | sha256sum }}
        presto-jmx-con***REMOVED***g-hash: {{ include (print $.Template.BasePath "/presto-jmx-con***REMOVED***g.yaml") . | sha256sum }}
{{- if .Values.spec.presto.annotations }}
{{ toYaml .Values.spec.presto.annotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.spec.presto.securityContext }}
      securityContext:
{{ toYaml .Values.spec.presto.securityContext | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.worker.af***REMOVED***nity }}
      af***REMOVED***nity:
{{ toYaml .Values.spec.presto.worker.af***REMOVED***nity | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spec.presto.worker.nodeSelector | indent 8 }}
{{- end }}
      initContainers:
      - name: copy-presto-con***REMOVED***g
        image: "{{ .Values.spec.presto.image.repository }}:{{ .Values.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.spec.presto.image.pullPolicy }}
        command: ['bash', '-c']
        # Copy the mounted con***REMOVED***guration data into the presto-etc emptyDir volume so we can write to the con***REMOVED***g ***REMOVED***les
        args: ['cp -v -L -r -f /presto-etc/* /opt/presto/presto-server/etc/']
        env:
{{- include "presto-common-env" . | indent 8 }}
        volumeMounts:
        - name: presto-etc
          mountPath: /opt/presto/presto-server/etc
        - name: presto-worker-con***REMOVED***g
          mountPath: /presto-etc
        - name: presto-catalog-con***REMOVED***g
          mountPath: /presto-etc/catalog
        - name: presto-data
          mountPath: /var/presto/data
        resources:
{{ toYaml .Values.spec.presto.worker.resources | indent 10 }}
      containers:
      - name: presto
        image: "{{ .Values.spec.presto.image.repository }}:{{ .Values.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.spec.presto.image.pullPolicy }}
        command: ['/presto-common/entrypoint.sh']
        args: ['/opt/presto/presto-server/bin/launcher', 'run']
        env:
        - name: JAVA_MAX_MEM_RATIO
          value: "{{ .Values.spec.presto.worker.con***REMOVED***g.jvm.percentMemoryLimitAsHeap }}"
          optional: true
{{- include "presto-common-env" . | indent 8 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: presto-etc
          mountPath: /opt/presto/presto-server/etc
        - name: presto-common-con***REMOVED***g
          mountPath: /presto-common
        - name: presto-jmx-con***REMOVED***g
          mountPath: /opt/jmx_exporter/con***REMOVED***g
        - name: presto-data
          mountPath: /var/presto/data
        - name: presto-logs
          mountPath: /var/presto/logs
{{- if .Values.spec.con***REMOVED***g.sharedVolume.enabled }}
        - name: hive-warehouse-data
          mountPath: {{ .Values.spec.con***REMOVED***g.sharedVolume.mountPath }}
{{- end }}
        resources:
{{ toYaml .Values.spec.presto.worker.resources | indent 10 }}
      volumes:
      - name: presto-worker-con***REMOVED***g
        con***REMOVED***gMap:
          name: presto-worker-con***REMOVED***g
      - name: presto-common-con***REMOVED***g
        con***REMOVED***gMap:
          name: presto-common-con***REMOVED***g
          defaultMode: 0774
      - name: presto-catalog-con***REMOVED***g
        secret:
          secretName: presto-catalog-con***REMOVED***g
      - name: presto-jmx-con***REMOVED***g
        con***REMOVED***gMap:
          name: presto-jmx-con***REMOVED***g
      - name: presto-etc
        emptyDir: {}
      - name: presto-data
        emptyDir: {}
      - name: presto-logs
        emptyDir: {}
{{- if .Values.spec.con***REMOVED***g.sharedVolume.enabled }}
      - name: hive-warehouse-data
        persistentVolumeClaim:
          claimName: {{ .Values.spec.con***REMOVED***g.sharedVolume.persistentVolumeClaimName }}
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: presto
{{- if .Values.spec.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.spec.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.spec.presto.worker.terminationGracePeriodSeconds }}
