apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: presto
  name: presto
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: 1
  selector:
  template:
    metadata:
      labels:
       app: presto
       presto: coordinator
      annotations:
        presto-config-hash: {{ include (print $.Template.BasePath "/presto-config.yaml") . | sha256sum }}
        presto-secrets-hash: {{ include (print $.Template.BasePath "/presto-secrets.yaml") . | sha256sum }}
    spec:
      securityContext:
{{ toYaml .Values.presto.securityContext | indent 8 }}
      containers:
      - name: presto
        image: "{{ .Values.presto.image.repository }}:{{ .Values.presto.image.tag }}"
        imagePullPolicy: {{ .Values.presto.image.pullPolicy }}
        env:
        - name: "HIVE_CATALOG_hive_s3_aws___access___key"
          valueFrom:
            secretKeyRef:
              name: presto-secrets
              key: aws-access-key-id
        - name: "HIVE_CATALOG_hive_s3_aws___secret___key"
          valueFrom:
            secretKeyRef:
              name: presto-secrets
              key: aws-secret-access-key
        - name: PRESTO_CONF_discovery_uri
          value: "http://presto:8080"
        - name: PRESTO_LOG_com_facebook_presto
          valueFrom:
            configMapKeyRef:
              name: presto-config
              key: log-level
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: presto
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: presto
              resource: limits.memory
        - name: JAVA_MAX_MEM_RATIO
          value: "50"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: presto-data
          mountPath: /var/presto/data
        resources:
{{ toYaml .Values.presto.resources | indent 10 }}
      volumes:
      - name: presto-data
        emptyDir: {}
      imagePullSecrets:
      - name: coreos-pull-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: presto
      terminationGracePeriodSeconds: {{ .Values.presto.terminationGracePeriodSeconds }}
