{{- if .Values.hadoop.spec.con***REMOVED***g.s3Compatible.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-s3-compatible-credentials
data:
{{- if .Values.hadoop.spec.con***REMOVED***g.s3Compatible.accessKeyID }}
  aws-access-key-id: {{ .Values.hadoop.spec.con***REMOVED***g.s3Compatible.accessKeyID | b64enc | quote}}
{{- end}}
{{- if .Values.hadoop.spec.con***REMOVED***g.s3Compatible.secretAccessKey }}
  aws-secret-access-key: {{ .Values.hadoop.spec.con***REMOVED***g.s3Compatible.secretAccessKey | b64enc | quote}}
{{- end}}
{{- end -}}
