{{- if .Values.hadoop.spec.config.aws.createCredentialsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-aws-credentials
data:
{{- if .Values.hadoop.spec.config.aws.accessKeyID }}
  aws-access-key-id: {{ .Values.hadoop.spec.config.aws.accessKeyID | b64enc | quote}}
{{- end}}
{{- if .Values.hadoop.spec.config.aws.secretAccessKey }}
  aws-secret-access-key: {{ .Values.hadoop.spec.config.aws.secretAccessKey | b64enc | quote}}
{{- end}}
{{- end -}}
