{{- if index .Values.spec.config.defaultReportDataSources "aws-billing" -}}
apiVersion: chargeback.coreos.com/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "pod-memory-request-aws"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-memory-request-raw"
  - "node-memory-allocatable"
  dynamicReportQueries:
  - "aws-ec2-billing-data"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: string
  - name: namespace
    type: string
  - name: node
    type: string
  - name: data_start
    type: timestamp
  - name: data_end
    type: timestamp
  - name: pod_request_memory_byte_seconds
    type: double
  - name: pod_memory_usage_percent
    type: double
  - name: pod_cost
    type: double
  query: |
    WITH aws_billing_filtered AS (
      {| renderReportGenerationQuery "aws-ec2-billing-data" . |}
    ),
    aws_billing_sum AS (
        SELECT sum(aws_billing_filtered.period_cost * aws_billing_filtered.period_percent) as cluster_cost
        FROM aws_billing_filtered
    ),
    node_memory_allocatable AS (
      SELECT min("timestamp") as node_allocatable_data_start,
        max("timestamp") as node_allocatable_data_end,
        sum(node_allocatable_memory_byte_seconds) as node_allocatable_memory_byte_seconds
      FROM {| generationQueryViewName "node-memory-allocatable" |}
        WHERE "timestamp" >= timestamp '{|.Report.StartPeriod | prestoTimestamp |}'
        AND "timestamp" <= timestamp '{| .Report.EndPeriod | prestoTimestamp |}'
    ),
    pod_memory_consumption AS (
      SELECT pod,
             namespace,
             node,
             min("timestamp") as data_start,
             max("timestamp") as data_end,
             sum(pod_request_memory_byte_seconds) as pod_request_memory_byte_seconds
      FROM {| generationQueryViewName "pod-memory-request-raw" |}
      WHERE "timestamp" >= timestamp '{|.Report.StartPeriod | prestoTimestamp |}'
      AND "timestamp" <= timestamp '{| .Report.EndPeriod | prestoTimestamp |}'
      GROUP BY pod, namespace, node
    ),
    cluster_usage AS (
        SELECT pod_memory_consumption.*,
               pod_memory_consumption.pod_request_memory_byte_seconds / node_memory_allocatable.node_allocatable_memory_byte_seconds as pod_memory_usage_percent
        FROM pod_memory_consumption
        CROSS JOIN node_memory_allocatable
        ORDER BY pod_memory_consumption.pod_request_memory_byte_seconds DESC
    )
    SELECT
      timestamp '{| .Report.StartPeriod| prestoTimestamp |}' AS period_start,
      timestamp '{| .Report.EndPeriod | prestoTimestamp |}' AS period_end,
      cluster_usage.*,
      aws_billing_sum.cluster_cost * cluster_usage.pod_memory_usage_percent as pod_cost
    FROM cluster_usage
    CROSS JOIN aws_billing_sum

---

apiVersion: chargeback.coreos.com/v1alpha1
kind: ReportGenerationQuery
metadata:
  name: "pod-memory-usage-aws"
  labels:
    operator-metering: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  reportQueries:
  - "pod-memory-usage-raw"
  - "node-memory-allocatable"
  dynamicReportQueries:
  - "aws-ec2-billing-data"
  view:
    disabled: true
  columns:
  - name: period_start
    type: timestamp
    unit: date
  - name: period_end
    type: timestamp
    unit: date
  - name: pod
    type: string
  - name: namespace
    type: string
  - name: node
    type: string
  - name: data_start
    type: timestamp
  - name: data_end
    type: timestamp
  - name: pod_usage_memory_byte_seconds
    type: double
  - name: pod_memory_usage_percent
    type: double
  - name: pod_cost
    type: double
  query: |
    WITH aws_billing_filtered AS (
      {| renderReportGenerationQuery "aws-ec2-billing-data" . |}
    ),
    aws_billing_sum AS (
        SELECT sum(aws_billing_filtered.period_cost * aws_billing_filtered.period_percent) as cluster_cost
        FROM aws_billing_filtered
    ),
    node_memory_allocatable AS (
      SELECT min("timestamp") as node_allocatable_data_start,
        max("timestamp") as node_allocatable_data_end,
        sum(node_allocatable_memory_byte_seconds) as node_allocatable_memory_byte_seconds
      FROM {| generationQueryViewName "node-memory-allocatable" |}
        WHERE "timestamp" >= timestamp '{|.Report.StartPeriod | prestoTimestamp |}'
        AND "timestamp" <= timestamp '{| .Report.EndPeriod | prestoTimestamp |}'
    ),
    pod_memory_consumption AS (
      SELECT pod,
             namespace,
             node,
             min("timestamp") as data_start,
             max("timestamp") as data_end,
             sum(pod_usage_memory_byte_seconds) as pod_usage_memory_byte_seconds
      FROM {| generationQueryViewName "pod-memory-usage-raw" |}
      WHERE "timestamp" >= timestamp '{|.Report.StartPeriod | prestoTimestamp |}'
      AND "timestamp" <= timestamp '{| .Report.EndPeriod | prestoTimestamp |}'
      GROUP BY pod, namespace, node
    ),
    cluster_usage AS (
        SELECT pod_memory_consumption.*,
               pod_memory_consumption.pod_usage_memory_byte_seconds / node_memory_allocatable.node_allocatable_memory_byte_seconds as pod_memory_usage_percent
        FROM pod_memory_consumption
        CROSS JOIN node_memory_allocatable
        ORDER BY pod_memory_consumption.pod_usage_memory_byte_seconds DESC
    )
    SELECT
      timestamp '{| .Report.StartPeriod| prestoTimestamp |}' AS period_start,
      timestamp '{| .Report.EndPeriod | prestoTimestamp |}' AS period_end,
      cluster_usage.*,
      aws_billing_sum.cluster_cost * cluster_usage.pod_memory_usage_percent as pod_cost
    FROM cluster_usage
    CROSS JOIN aws_billing_sum
{{- end -}}
