apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prestotables.metering.openshift.io
spec:
  group: metering.openshift.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
  scope: Namespaced
  names:
    plural: prestotables
    singular: prestotable
    kind: PrestoTable
  additionalPrinterColumns:
  - name: Table Name
    type: string
    JSONPath: .status.tableName

