spec:
  replicas: 1
  image:
    repository: quay.io/coreos/metering-reporting-operator
    tag: latest
    pullPolicy: Always

  config:
    awsAccessKeyID: ""
    awsSecretAccessKey: ""
    awsCredentialsSecretName: reporting-operator-aws-credentials-secrets
    createAwsCredentialsSecret: true

    tls:
      enabled: false
      createSecret: false
      certificateData: null
      privateKeyData: null
      secretName: reporting-operator-api-tls-secrets

    metricsTLS:
      enabled: false
      createSecret: false
      certificateData: null
      privateKeyData: null
      secretName: reporting-operator-metrics-tls-secrets

    defaultStorage:
      create: true
      name: "hive-hdfs"
      isDefault: true
      type: "hive"
      hive:
        tableProperties:
          location: "hdfs://hdfs-namenode-proxy:8020/operator_metering/storage/"

    defaultReportDataSources:
      pod-request-cpu-cores:
        spec:
          promsum:
            query: "pod-request-cpu-cores"
      pod-limit-cpu-cores:
        spec:
          promsum:
            query: "pod-limit-cpu-cores"
      pod-usage-cpu-cores:
        spec:
          promsum:
            query: "pod-usage-cpu-cores"

      pod-request-memory-bytes:
        spec:
          promsum:
            query: "pod-request-memory-bytes"
      pod-limit-memory-bytes:
        spec:
          promsum:
            query: "pod-limit-memory-bytes"
      pod-usage-memory-bytes:
        spec:
          promsum:
            query: "pod-usage-memory-bytes"

      node-allocatable-memory-bytes:
        spec:
          promsum:
            query: "node-allocatable-memory-bytes"
      node-capacity-memory-bytes:
        spec:
          promsum:
            query: "node-capacity-memory-bytes"

      node-allocatable-cpu-cores:
        spec:
          promsum:
            query: "node-allocatable-cpu-cores"
      node-capacity-cpu-cores:
        spec:
          promsum:
            query: "node-capacity-cpu-cores"

    prometheusURL: ""
    prestoHost: "presto:8080"
    hiveHost: "hive-server:10000"

    promsumPollInterval: "5m"
    promsumChunkSize: "5m"
    promsumStepSize: "60s"

    logReports: "false"
    logDDLQueries: "false"
    logDMLQueries: "false"
    disablePromsum: "false"

    leaderLeaseDuration: "60s"

  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "150Mi"
      cpu: "100m"

  updateStrategy:
    type: RollingUpdate

  readinessProbe:
   initialDelaySeconds: 60
   timeoutSeconds: 60
   periodSeconds: 10
   successThreshold: 1
   failureThreshold: 6
   httpGet:
     path: /ready
     port: 8080
     scheme: HTTP

  livenessProbe:
   initialDelaySeconds: 120
   timeoutSeconds: 60
   periodSeconds: 60
   successThreshold: 1
   failureThreshold: 5
   httpGet:
     path: /healthy
     port: 8080
     scheme: HTTP

  labels: {}
  annotations: {}
  nodeSelector: {}

  service:
    annotations: {}
    type: ClusterIP
    nodePort: null

  metricsService:
    annotations: {}

  route:
    enabled: false
    name: metering

  authProxy:
    enabled: false
    image:
      repository: openshift/oauth-proxy
      tag: v1.1.0
      pullPolicy: Always

    htpasswdSecretName: reporting-operator-auth-proxy-htpasswd
    createHtpasswdSecret: true
    htpasswdData: ""

    cookieSecretName: reporting-operator-auth-proxy-cookie-seed
    createCookieSecret: true
    cookieSeed: ""

    createAuthProxyClusterRole: false
    subjectAccessReviewEnabled: false
    delegateURLsEnabled: false

    authenticatedEmailsSecretName: reporting-operator-auth-proxy-authenticated-emails
    authenticatedEmailsEnabled: false
    createAuthenticatedEmailsSecret: true
    authenticatedEmailsData: ""

    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "50Mi"
        cpu: "50m"
