apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportqueries.metering.openshift.io
  annotations:
    catalog.app.coreos.com/displayName: Metering Report Query
    catalog.app.coreos.com/description: A SQL query used by Metering to generate reports.
    catalog.app.coreos.com/weight: "2"
spec:
  group: metering.openshift.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: reportqueries
    singular: reportquery
    kind: ReportQuery
    shortNames:
    - rq
  additionalPrinterColumns:
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
