apiVersion: chargeback.coreos.com/prealpha
kind: Report
metadata:
  name: pod-memory-usage-by-node
spec:
  reportingStart: '2017-01-01T00:00:00Z'
  reportingEnd: '2017-12-30T23:59:59Z'
  generationQuery: "pod-memory-usage-by-node"
  output:
    bucket: "REPLACEME"
    pre***REMOVED***x: "reports_node_pod_memory"
