apiVersion: chargeback.coreos.com/prealpha
kind: Report
metadata:
  name: pod-cpu-usage-by-node
spec:
  reportingStart: '2017-01-01T00:00:00Z'
  reportingEnd: '2017-12-30T23:59:59Z'
  generationQuery: "pod-cpu-usage-by-node"
  output:
    bucket: "REPLACEME"
    prefix: "reports_node_pod_cpu"
