apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportdatastores.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: prealpha
  scope: Namespaced
  names:
    plural: reportdatastores
    singular: reportdatastore
    kind: ReportDataStore
