apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: presto-coordinator
  labels:
    app: presto
    presto: coordinator
spec:
  replicas: 1
  serviceName: presto-nodes
  selector:
    matchLabels:
      app: presto
      presto: coordinator
{{- if .Values.presto.spec.presto.labels }}
{{ toYaml .Values.presto.spec.presto.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: presto
        presto: coordinator
{{- if .Values.presto.spec.presto.labels }}
{{ toYaml .Values.presto.spec.presto.labels | indent 8 }}
{{- end }}
      annotations:
        presto-coordinator-config-hash: {{ include (print $.Template.BasePath "/presto/presto-coordinator-config.yaml") . | sha256sum }}
        presto-common-config-hash: {{ include (print $.Template.BasePath "/presto/presto-common-config.yaml") . | sha256sum }}
        presto-catalog-config-hash: {{ include (print $.Template.BasePath "/presto/presto-catalog-config-secret.yaml") . | sha256sum }}
        presto-jmx-config-hash: {{ include (print $.Template.BasePath "/presto/presto-jmx-config.yaml") . | sha256sum }}
{{- if .Values.presto.spec.presto.annotations }}
{{ toYaml .Values.presto.spec.presto.annotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.presto.spec.presto.securityContext }}
      securityContext:
{{ toYaml .Values.presto.spec.presto.securityContext | indent 8 }}
{{- end }}
{{- if .Values.presto.spec.presto.coordinator.affinity }}
      affinity:
{{ toYaml .Values.presto.spec.presto.coordinator.affinity | indent 8 }}
{{- end }}
{{- if .Values.presto.spec.presto.coordinator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.presto.spec.presto.coordinator.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.presto.spec.presto.coordinator.tolerations }}
      tolerations:
{{ toYaml .Values.presto.spec.presto.coordinator.tolerations | indent 8 }}
{{- end }}
      initContainers:
      - name: copy-presto-config
        image: "{{ .Values.presto.spec.presto.image.repository }}:{{ .Values.presto.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.presto.spec.presto.image.pullPolicy }}
        command: ['/presto-common/initialize_presto.sh']
        # Copy the mounted configuration data into the presto-etc emptyDir volume so we can write to the config files
        env:
{{- if .Values.presto.spec.presto.config.tls.enabled }}
        - name: PRESTO_SERVER_KEYFILE
          value: /presto-server/tls.key
        - name: PRESTO_SERVER_CRTFILE
          value: /presto-server/tls.crt
        - name: PRESTO_SERVER_PEM
          value: /opt/presto/tls/server.pem
        - name: PRESTO_KEYSTORE_PEM
          value: /opt/presto/tls/keystore.pem
        - name: PRESTO_TRUSTSTORE_PEM
          value: /opt/presto/tls/truststore.pem
        - name: PRESTO_CA_CRTFILE
          value: /presto-ca/tls.crt
{{- if .Values.presto.spec.presto.config.auth.enabled }}
        - name: PRESTO_CLIENT_KEYFILE
          value: /presto-client/tls.key
        - name: PRESTO_CLIENT_CRTFILE
          value: /presto-client/tls.crt
{{- end }}
{{- end }}
{{- include "presto-common-env" . | indent 8 }}
        volumeMounts:
        - name: presto-etc
          mountPath: /opt/presto/presto-server/etc
        - name: presto-coordinator-config
          mountPath: /presto-etc
        - name: presto-catalog-config
          mountPath: /presto-etc/catalog
        - name: presto-data
          mountPath: /var/presto/data
        - name: presto-common-config
          mountPath: /presto-common
{{- if .Values.presto.spec.presto.config.tls.enabled }}
        - name: presto-tls
          mountPath: /opt/presto/tls
        - name: presto-server-pem
          mountPath: /presto-server
        - name: presto-ca-pem
          mountPath: /presto-ca
{{- if .Values.presto.spec.presto.config.auth.enabled }}
        - name: presto-client-pem
          mountPath: /presto-client
{{- end }}
{{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      containers:
      - name: presto
        image: "{{ .Values.presto.spec.presto.image.repository }}:{{ .Values.presto.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.presto.spec.presto.image.pullPolicy }}
        command: ['/presto-common/entrypoint.sh']
        args: ['/opt/presto/presto-server/bin/launcher', 'run']
        env:
        - name: JAVA_MAX_MEM_RATIO
          value: "{{ .Values.presto.spec.presto.coordinator.config.jvm.percentMemoryLimitAsHeap }}"
{{- include "presto-common-env" . | indent 8 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: presto-etc
          mountPath: /opt/presto/presto-server/etc
        - name: presto-common-config
          mountPath: /presto-common
        - name: presto-jmx-config
          mountPath: /opt/jmx_exporter/config
        - name: presto-data
          mountPath: /var/presto/data
        - name: presto-logs
          mountPath: /var/presto/logs
{{- if .Values.presto.spec.presto.config.tls.enabled }}
        - name: presto-tls
          mountPath: /opt/presto/tls
{{- end }}
{{- if .Values.presto.spec.config.sharedVolume.enabled }}
        - name: hive-warehouse-data
          mountPath: {{ .Values.presto.spec.config.sharedVolume.mountPath }}
{{- end }}
        resources:
{{ toYaml .Values.presto.spec.presto.coordinator.resources | indent 10 }}
      volumes:
      - name: presto-coordinator-config
        configMap:
          name: presto-coordinator-config
      - name: presto-common-config
        configMap:
          name: presto-common-config
          defaultMode: 0774
      - name: presto-catalog-config
        secret:
          secretName: presto-catalog-config
      - name: presto-jmx-config
        configMap:
          name: presto-jmx-config
      - name: presto-etc
        emptyDir: {}
      - name: presto-data
        emptyDir: {}
      - name: presto-logs
        emptyDir: {}
{{- if .Values.presto.spec.presto.config.tls.enabled }}
      - name: presto-tls
        emptyDir: {}
      - name: presto-server-pem
        secret:
          secretName: {{ .Values.presto.spec.presto.config.tls.serverSecretName }}
      - name: presto-ca
        emptyDir: {}
      - name: presto-ca-pem
        secret:
          secretName: {{ .Values.presto.spec.presto.config.tls.rootCASecretName }}
{{- if .Values.presto.spec.presto.config.auth.enabled }}
      - name: presto-client-pem
        secret:
          secretName: {{ .Values.presto.spec.presto.config.auth.clientSecretName }}
{{- end }}
{{- end }}
{{- if .Values.presto.spec.config.sharedVolume.enabled }}
      - name: hive-warehouse-data
        persistentVolumeClaim:
          claimName: {{ .Values.presto.spec.config.sharedVolume.persistentVolumeClaimName }}
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: presto
{{- if .Values.presto.spec.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.presto.spec.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.presto.spec.presto.coordinator.terminationGracePeriodSeconds }}
