apiVersion: v1
kind: ConfigMap
metadata:
  name: chargeback-config
  labels:
    app: chargeback
data:
  aws-region: "us-west-1"
  log-reports: "false"
  log-ddl-queries: "false"
  log-dml-queries: "false"
  disable-promsum: ""
  prometheus-url: "http://prometheus.tectonic-system.svc.cluster.local:9090/"
  promsum-poll-interval: "5m"
  promsum-chunk-size: "5m"
  promsum-step-size: "60s"
