apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: chargeback
rules:
- apiGroups: ["chargeback.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["cron.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: chargeback
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chargeback
subjects:
- kind: ServiceAccount
  name: chargeback
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chargeback
