apiVersion: chargeback.coreos.com/prealpha
kind: Report
metadata:
  name: default
spec:
  reportingStart: '2017-07-02T00:00:00Z'
  reportingEnd: '2017-07-29T00:00:00Z'
  chargeback:
    bucket: coreos-team-chargeback
    prefix: august-promsum-data
  aws:
    bucket: coreos-team-chargeback
    reportName: team-chargeback-testing
    reportPrefix: coreos-detailed-billing/coreosinc/coreos-detailed-billing-001
  output:
    bucket: coreos-team-chargeback
    prefix: billingReport4
