apiVersion: cron.coreos.com/v1
kind: Cron
metadata:
  name: 1-minute
spec:
  suspend: false
  schedule: "@every 20s"
  reportTemplate:
    metadata:
      generateName: minute
    spec:
      reportingStart: '2017-07-28T00:00:00Z'
      reportingEnd: '2017-07-29T00:00:00Z'
      chargeback:
        bucket: coreos-team-chargeback
        prefix: july-pod-data
      aws:
        bucket: coreos-team-chargeback
        prefix: coreos-detailed-billing/coreosinc/coreos-detailed-billing-001/team-chargeback-testing
      output:
        bucket: coreos-team-chargeback
        prefix: billingReport3
