---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.spec.con***REMOVED***g.allNamespaces }}
kind: ClusterRole
{{- ***REMOVED*** }}
kind: Role
{{- end }}
metadata:
{{- if .Values.spec.con***REMOVED***g.allNamespaces }}
{{/* Pre***REMOVED***x the namespace to the name of the ClusterRole since there could be multiple copies of this being installed */}}
  name: {{ .Release.Namespace }}-reporting-operator
{{- ***REMOVED*** }}
  name: reporting-operator
{{- end }}
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
rules:
# grants access to all core metering types which the reporting-operator uses
- apiGroups: ["metering.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
# grants access to leader election lock based on con***REMOVED***gmaps
- apiGroups:
  - ""
  resources:
  - con***REMOVED***gmaps
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
# grants access to creating and updating events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.spec.con***REMOVED***g.allNamespaces }}
kind: ClusterRoleBinding
{{- ***REMOVED*** }}
kind: RoleBinding
{{- end }}
metadata:
{{- if .Values.spec.con***REMOVED***g.allNamespaces }}
{{/* Pre***REMOVED***x the namespace to the name of the ClusterRole since there could be multiple copies of this being installed */}}
  name: {{ .Release.Namespace }}-reporting-operator
{{- ***REMOVED*** }}
  name: reporting-operator
{{- end }}
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.spec.con***REMOVED***g.allNamespaces }}
  kind: ClusterRole
  name: {{ .Release.Namespace }}-reporting-operator
{{- ***REMOVED*** }}
  kind: Role
  name: reporting-operator
{{- end }}
subjects:
- kind: ServiceAccount
  name: reporting-operator
  namespace: {{ .Release.Namespace }}

---

{{- if .Values.spec.con***REMOVED***g.createClusterMonitoringViewClusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
{{- /* Pre***REMOVED***x the namespace to the name of the ClusterRole since there could be multiple copies of this being installed */}}
  name: {{ .Release.Namespace }}-reporting-operator-cluster-monitoring-view
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if .Values.spec.con***REMOVED***g.createClusterMonitoringViewClusterRole }}
  name: {{ .Release.Namespace }}-reporting-operator-cluster-monitoring-view
{{- ***REMOVED*** }}
  name: cluster-monitoring-view
{{- end }}
subjects:
- kind: ServiceAccount
  name: reporting-operator
  namespace: {{ .Release.Namespace }}
{{- end }}

---

{{- if .Values.spec.con***REMOVED***g.createClusterMonitoringViewClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
{{- /* Pre***REMOVED***x the namespace to the name of the ClusterRole since there could be multiple copies of this being installed */}}
  name: {{ .Release.Namespace }}-reporting-operator-cluster-monitoring-view
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
rules:
# grants access to metrics data
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
{{- end }}
