csv:
  name : metering-operator.vlatest
  displayName: Metering
  description: Metering can generate reports based on historical usage data from a cluster, providing accountability for how resources have been used.
  keywords: ['metering', 'metrics', 'reporting']
  version: latest
  maturity: alpha
  maintainers:
  - name: Red Hat
    email: sd-operator-metering@redhat.com
  provider:
    name: Red Hat
  labels:
    olm-status-descriptors: metering-operator.vlatest
    olm-owner-metering: metering-operator
  matchLabels:
    olm-owner-metering: metering-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false

packageName: metering
channels:
- name: alpha
  currentCSV: metering-operator.vlatest

subscriptionName: metering
subscriptionChannel: alpha
subscriptionCatalogSource: metering-operators
subscriptionCatalogSourceNamespace: openshift-metering

operatorGroupName: metering-operators
operatorGroupTargetNamespaces: ["openshift-metering"]

catalogSourceConfigName: metering-operators
catalogSourceConfigNamespace: openshift-marketplace
catalogTargetNamespace: "openshift-metering"

