apiVersion: v1
kind: Service
metadata:
  name: hive-server
  labels:
    app: hive
    hive: server
spec:
  ports:
  - name: thrift
    port: 10000
  - name: ui
    port: 10002
  - name: metrics
    port: 8082
  - name: ghostunnel
    port: 10001
  selector:
    app: hive
    hive: server
  sessionAffinity: None
  type: ClusterIP
