{{- if .Values.hive.spec.config.azure.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: hive-azure-credentials
data:
{{- if .Values.hive.spec.config.azure.storageAccountName }}
  azure-storage-account-name: {{ .Values.hive.spec.config.azure.storageAccountName | b64enc | quote}}
{{- end}}
{{- if .Values.hive.spec.config.azure.secretAccessKey }}
  azure-secret-access-key: {{ .Values.hive.spec.config.azure.secretAccessKey | b64enc | quote}}
{{- end}}
{{- end -}}
