{{- if .Values.hive.spec.server.config.tls.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hive.spec.server.config.tls.secretName }}
  labels:
    app: hive
    hive: server
type: Opaque
data:
  tls.crt: {{ .Values.hive.spec.server.config.tls.certificate | b64enc | quote }}
  tls.key: {{ .Values.hive.spec.server.config.tls.key | b64enc | quote }}
  ca.crt: {{.Values.hive.spec.server.config.tls.caCertificate | b64enc | quote }}
{{- end -}}
