---
# Source: helm-operator/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chargebacks.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: chargebacks
    singular: chargeback
    kind: Chargeback
    listKind: ChargebackList
