apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: promsum
spec:
  selector:
    matchLabels:
      app: promsum
  template:
    metadata:
      name: promsum
      labels:
        app: promsum
    spec:
      containers:
      - name: promsum
        image: quay.io/coreos/promsum:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: chargeback-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chargeback-secrets
              key: aws-secret-access-key
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: chargeback-config
              key: aws-region
        - name: PROM
          valueFrom:
            configMapKeyRef:
              name: chargeback-config
              key: prometheus-url
        - name: POLL_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: chargeback-config
              key: promsum-poll-interval
      restartPolicy: Always
      serviceAccount: promsum
