apiVersion: chargeback.coreos.com/v1alpha1
kind: ReportDataStore
metadata:
  name: "pod-cpu-usage"
  labels:
    tectonic-chargeback: "true"
spec:
  promsum:
    storage:
      s3:
        bucket: "REPLACEME"
        prefix: "promsum/cpu_by_pod"
    queries:
    - "get-cpu-by-pod"
